/**
 * SSE fixtures: Context compaction flow
 * Simulates a conversation that triggers compaction due to high token usage.
 *
 * Round 1: Normal text response with extremely high token count (triggers compaction)
 * Round 2: Compaction agent's summary response
 * Round 3: Continuation response after compaction
 *
 * Confirmation text generated by gemini-3-flash LLM.
 */

const INITIAL_RESPONSE =
    "您好！我很乐意为您分析。我会通过扫描代码库的目录结构和核心配置文件，为您梳理出该项目的整体架构。"

const COMPACTION_SUMMARY =
    "## Goal\\n分析并总结该项目的设计模式与核心模块依赖关系。\\n## Accomplished\\n已完成对代码库根目录的深度扫描，并识别出了项目的入口文件及其关键技术栈。\\n## Relevant files\\n- src/app/main.ts\\n- config/settings.yaml"

const CONTINUATION_RESPONSE = "好的，我可以继续帮你分析。请问你想了解哪方面？"

export { INITIAL_RESPONSE, COMPACTION_SUMMARY, CONTINUATION_RESPONSE }

/**
 * Build SSE fixtures for the compaction test.
 *
 * The first response sets input_tokens to a very high value (200000)
 * to trigger SessionCompaction.isOverflow() regardless of the model's
 * actual context limit.
 */
export function buildCompactionFixtures() {
    // ── Round 1: Initial response with high token count ───────────────
    const initialBody = [
        `data: {"type":"response.created","response":{"id":"resp_cmp001","object":"response","created_at":1700000000,"model":"gpt-4o","status":"in_progress","output":[]}}\n\n`,
        `data: {"type":"response.output_item.added","output_index":0,"item":{"type":"message","id":"msg_cmp001","role":"assistant","content":[]}}\n\n`,
        `data: {"type":"response.content_part.added","output_index":0,"content_index":0,"part":{"type":"output_text","text":""}}\n\n`,
        `data: {"type":"response.output_text.delta","output_index":0,"content_index":0,"item_id":"msg_cmp001","delta":"${INITIAL_RESPONSE}"}\n\n`,
        `data: {"type":"response.output_text.done","output_index":0,"content_index":0,"text":"${INITIAL_RESPONSE}"}\n\n`,
        `data: {"type":"response.content_part.done","output_index":0,"content_index":0,"part":{"type":"output_text","text":"${INITIAL_RESPONSE}"}}\n\n`,
        `data: {"type":"response.output_item.done","output_index":0,"item":{"type":"message","id":"msg_cmp001","role":"assistant","content":[{"type":"output_text","text":"${INITIAL_RESPONSE}"}]}}\n\n`,
        // Key: set extremely high input_tokens to trigger compaction
        `data: {"type":"response.completed","response":{"id":"resp_cmp001","object":"response","created_at":1700000000,"model":"gpt-4o","status":"completed","output":[{"type":"message","id":"msg_cmp001","role":"assistant","content":[{"type":"output_text","text":"${INITIAL_RESPONSE}"}]}],"usage":{"input_tokens":200000,"output_tokens":50,"total_tokens":200050,"output_tokens_details":{"reasoning_tokens":0},"input_tokens_details":{"cached_tokens":0}}}}\n\n`,
    ].join("")

    // ── Round 2: Compaction summary response ──────────────────────────
    const compactionBody = [
        `data: {"type":"response.created","response":{"id":"resp_cmp002","object":"response","created_at":1700000001,"model":"gpt-4o","status":"in_progress","output":[]}}\n\n`,
        `data: {"type":"response.output_item.added","output_index":0,"item":{"type":"message","id":"msg_cmp002","role":"assistant","content":[]}}\n\n`,
        `data: {"type":"response.content_part.added","output_index":0,"content_index":0,"part":{"type":"output_text","text":""}}\n\n`,
        `data: {"type":"response.output_text.delta","output_index":0,"content_index":0,"item_id":"msg_cmp002","delta":"${COMPACTION_SUMMARY}"}\n\n`,
        `data: {"type":"response.output_text.done","output_index":0,"content_index":0,"text":"${COMPACTION_SUMMARY}"}\n\n`,
        `data: {"type":"response.content_part.done","output_index":0,"content_index":0,"part":{"type":"output_text","text":"${COMPACTION_SUMMARY}"}}\n\n`,
        `data: {"type":"response.output_item.done","output_index":0,"item":{"type":"message","id":"msg_cmp002","role":"assistant","content":[{"type":"output_text","text":"${COMPACTION_SUMMARY}"}]}}\n\n`,
        `data: {"type":"response.completed","response":{"id":"resp_cmp002","object":"response","created_at":1700000001,"model":"gpt-4o","status":"completed","output":[{"type":"message","id":"msg_cmp002","role":"assistant","content":[{"type":"output_text","text":"${COMPACTION_SUMMARY}"}]}],"usage":{"input_tokens":500,"output_tokens":100,"total_tokens":600,"output_tokens_details":{"reasoning_tokens":0},"input_tokens_details":{"cached_tokens":0}}}}\n\n`,
    ].join("")

    // ── Round 3: Continuation response ────────────────────────────────
    const continuationBody = [
        `data: {"type":"response.created","response":{"id":"resp_cmp003","object":"response","created_at":1700000002,"model":"gpt-4o","status":"in_progress","output":[]}}\n\n`,
        `data: {"type":"response.output_item.added","output_index":0,"item":{"type":"message","id":"msg_cmp003","role":"assistant","content":[]}}\n\n`,
        `data: {"type":"response.content_part.added","output_index":0,"content_index":0,"part":{"type":"output_text","text":""}}\n\n`,
        `data: {"type":"response.output_text.delta","output_index":0,"content_index":0,"item_id":"msg_cmp003","delta":"${CONTINUATION_RESPONSE}"}\n\n`,
        `data: {"type":"response.output_text.done","output_index":0,"content_index":0,"text":"${CONTINUATION_RESPONSE}"}\n\n`,
        `data: {"type":"response.content_part.done","output_index":0,"content_index":0,"part":{"type":"output_text","text":"${CONTINUATION_RESPONSE}"}}\n\n`,
        `data: {"type":"response.output_item.done","output_index":0,"item":{"type":"message","id":"msg_cmp003","role":"assistant","content":[{"type":"output_text","text":"${CONTINUATION_RESPONSE}"}]}}\n\n`,
        `data: {"type":"response.completed","response":{"id":"resp_cmp003","object":"response","created_at":1700000002,"model":"gpt-4o","status":"completed","output":[{"type":"message","id":"msg_cmp003","role":"assistant","content":[{"type":"output_text","text":"${CONTINUATION_RESPONSE}"}]}],"usage":{"input_tokens":300,"output_tokens":30,"total_tokens":330,"output_tokens_details":{"reasoning_tokens":0},"input_tokens_details":{"cached_tokens":0}}}}\n\n`,
    ].join("")

    return { initialBody, compactionBody, continuationBody }
}
